language: node_js

node_js:
    - "node"
    - "8"
    - "7"

sudo: false

git:
    submodules: false

before_script:
    - npm install

script:
    - npm test

env:
  - NODE_ENV="test"

after_success:
    - npm run coveralls
